substitutions:
  device: irrigation-1
  name: Irrigation A
  comment: "OBSOLETE | Outside, Well: Irrigation system"

esphome:
  name: mcu-${device}
  comment: ${comment}
  platform: ESP8266
  board: esp01_1m
  # on_boot:
  #   priority: -10
  #   then:
  #     - switch.turn_off: relay_1
  #     - delay: 2s
  #     - switch.turn_off: relay_2
  #     - delay: 2s
  #     - switch.turn_off: relay_3
  #     - delay: 2s
  #     - switch.turn_off: relay_4
  #     - delay: 2s
  #     - switch.turn_off: relay_5

packages:
  common: !include common/common_esp8266.yaml
  
# api:
#   services:
#     - service: program_morning
#       then:
#         - switch.turn_on: relay_1
#         - delay: 10minutes
#         - switch.turn_off: relay_1
#         - delay: 1minutes
#         - switch.turn_on: relay_2
#         - delay: 10minutes
#         - switch.turn_off: relay_2
#         - delay: 1minutes
#         - switch.turn_on: relay_3
#         - delay: 5minutes
#         # - switch.turn_on: relay_4
#         # - delay: 40minutes
#         - switch.turn_off: relay_3
#         - delay: 1minutes
#         - switch.turn_on: relay_1
#         - delay: 10minutes
#         - switch.turn_off: relay_1
#         - delay: 1minutes
#         - switch.turn_on: relay_2
#         - delay: 10minutes
#         - switch.turn_off: relay_2
#         - delay: 1minutes
#         - switch.turn_on: relay_3
#         - delay: 5minutes
#         # - switch.turn_on: relay_4
#         # - delay: 40minutes
#         - switch.turn_off: relay_3
#     - service: program_grass
#       then:
#         - switch.turn_on: relay_1
#         - delay: 5minutes
#         - switch.turn_off: relay_1
#         - delay: 1minutes
#         - switch.turn_on: relay_2
#         - delay: 5minutes
#         - switch.turn_off: relay_2
#     - service: patio
#       then:
#         - switch.turn_on: relay_5
#         - delay: 30sec
#         - switch.turn_off: relay_5

i2c:
  sda: 3
  scl: 1
  scan: true #false

# mcp23017:
#   - id: 'mcp23017_hub'
#     address: 0x20

pcf8574:
  - id: 'relay_module'
    address: 0x20
    pcf8575: false

# SONOFF 4ch Pro! Not R2!
# GPIO_KEY1,        // GPIO00 Button 1
# GPIO_USER,        // GPIO01 Serial RXD and Optional sensor
# GPIO_USER,        // GPIO02 Optional sensor
# GPIO_USER,        // GPIO03 Serial TXD and Optional sensor
# GPIO_REL3,        // GPIO04 Sonoff 4CH Red Led and Relay 3 (0 = Off, 1 = On)
# GPIO_REL2,        // GPIO05 Sonoff 4CH Red Led and Relay 2 (0 = Off, 1 = On)
#                   // GPIO06 (SD_CLK   Flash)
#                   // GPIO07 (SD_DATA0 Flash QIO/DIO/DOUT)
#                   // GPIO08 (SD_DATA1 Flash QIO/DIO/DOUT)
# GPIO_KEY2,        // GPIO09 Button 2
# GPIO_KEY3,        // GPIO10 Button 3
#                   // GPIO11 (SD_CMD   Flash)
# GPIO_REL1,        // GPIO12 Red Led and Relay 1 (0 = Off, 1 = On)
# GPIO_LED1_INV,    // GPIO13 Blue Led (0 = On, 1 = Off) - Link and Power status
# GPIO_KEY4,        // GPIO14 Button 4
# GPIO_REL4,        // GPIO15 Red Led and Relay 4 (0 = Off, 1 = On)

# binary_sensor:
  # - platform: gpio
  #   pin:
  #     number: GPIO0
  #     mode: INPUT_PULLUP
  #     inverted: True
  #   name: "Irrigation Button A1"
  #   id: button_1
  #   on_press:
  #     - switch.toggle: relay_1
  # - platform: gpio
  #   pin:
  #     number: GPIO9
  #     mode: INPUT_PULLUP
  #     inverted: True
  #   name: "Irrigation Button A2"
  #   id: button_2
  #   on_press:
  #     - switch.toggle: relay_2
  # - platform: gpio
  #   pin:
  #     number: GPIO10
  #     mode: INPUT_PULLUP
  #     inverted: True
  #   name: "Irrigation Button A3"
  #   id: button_3
  #   on_press:
  #     - switch.toggle: relay_3
  # - platform: gpio
  #   pin:
  #     number: GPIO14
  #     mode: INPUT_PULLUP
  #     inverted: True
  #   name: "Irrigation Button A4"
  #   id: button_4
  #   on_press:
  #     - switch.toggle: relay_4

# sensor:
  # - platform: dht
  #   pin: GPIO2
  #   temperature:
  #     name: "Well Shaft Temperature"
  #     id: 'well_temperature'
  #   humidity:
  #     name: "Well Shaft Humidity"
  #     id: 'well_humidity'
  #   model: 'DHT22'
  #   update_interval: 60s

# switch:
#   - platform: gpio
#     name: "Irrigation Valve A1"
#     pin: GPIO12
#     id: relay_1
#     interlock: &interlock_group [relay_1, relay_2, relay_3, relay_4, relay_5, relay_6, relay_7, relay_8]
#   - platform: gpio
#     name: "Irrigation Valve A2"
#     pin: GPIO5
#     id: relay_2
#     interlock: *interlock_group
#   - platform: gpio
#     name: "Irrigation Valve A3"
#     pin: GPIO4
#     id: relay_3
#     interlock: *interlock_group
#   - platform: gpio
#     name: "Irrigation Valve A4"
#     pin: GPIO15
#     id: relay_4
#     interlock: *interlock_group
#   - platform: gpio
#     name: "Irrigation Valve A5"
#     id: relay_5
#     interlock: *interlock_group
#     pin:
#       pcf8574: relay_module
#       number: 0
#       mode: OUTPUT
#       inverted: true
#   - platform: gpio
#     name: "Irrigation Valve A6"
#     id: relay_6
#     interlock: *interlock_group
#     pin:
#       pcf8574: relay_module
#       number: 1
#       mode: OUTPUT
#       inverted: true
#   - platform: gpio
#     name: "Irrigation Valve A7"
#     id: relay_7
#     interlock: *interlock_group
#     pin:
#       pcf8574: relay_module
#       number: 2
#       mode: OUTPUT
#       inverted: true
#   - platform: gpio
#     name: "Irrigation Valve A8"
#     id: relay_8
#     interlock: *interlock_group
#     pin:
#       pcf8574: relay_module
#       number: 3
#       mode: OUTPUT
#       inverted: true
      
# output:
#   - platform: esp8266_pwm
#     id: led_blue
#     pin: GPIO13
#     inverted: True

# light:
#   - platform: monochromatic
#     name: "Irrigation A Blue LED"
#     output: led_blue

time:
  - !include common/time/homeassistant.yaml