---
substitutions:
  device: apollo-dev #test
  name: Apollo DEV
  area: DEV
  comment: --

esphome:
  name: mcu-${device} #test
  friendly_name: ${name}
  area: ${area}
  comment: ${comment}

esp32:
  variant: esp32c6
  flash_size: 8MB
  framework:
    type: esp-idf

packages:
  common: !include common/common.yaml

api:
  # https://github.com/granadaxronos/120-SONG_NOKIA_RTTTL_RINGTONE_PLAYER_FOR_ARDUINO_UNO/blob/master/RTTTL_PLAYER/songs.h
  services:
    - service: play_rtttl
      variables:
        song: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song;'
  
switch:
  - platform: gpio
    id: accessory_power
    internal: true
    name: Accessory Power
    pin: 4
    restore_mode: ALWAYS_ON
    setup_priority: 2000

web_server:
  version: "3"

light:
  - platform: esp32_rmt_led_strip
    name: RGB LEDs
    pin: 14
    id: rgb_leds
    chipset: WS2812
    num_leds: 10
    rgb_order: GRB
    rmt_symbols: 48
    effects:
      # Use default parameters:
      - random:
      # Customize parameters
      - random:
          name: "My Slow Random Effect"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "My Fast Random Effect"
          transition_length: 4s
          update_interval: 5s
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:
  - platform: esp32_rmt_led_strip
    name: Onboard RGB LED
    pin: 5
    id: onboard_rgb_led
    chipset: WS2812
    num_leds: 1
    rgb_order: GRB
    rmt_symbols: 48

output:
  - platform: ledc
    pin: 18
    id: buzzer_output

rtttl:
  - output: buzzer_output
    id: rtttl_player

i2c:
  - scl: 0
    sda: 1
    id: i2c_1

sensor:
  - platform: aht10
    i2c_id: i2c_1
    variant: AHT20
    humidity:
      name: Humidity
      id: aht20_humidity
      device_class: humidity
      unit_of_measurement: "%"
      accuracy_decimals: 2
      force_update: false
      state_class: measurement
    temperature:
      name: Temperature
      id: aht20_temperature
      device_class: temperature
      unit_of_measurement: °C
      accuracy_decimals: 2
      force_update: false
      state_class: measurement
    id: aht20
