substitutions:
  device: cam-1
  name: Cam 1
  comment: "DEV: Camera"
  
esphome:
  name: mcu-${device}
  comment: ${comment}

esp32:
  board: esp32cam
  framework:
    # type: arduino
    type: esp-idf
    # version: 2.0.14
    # platform_version: 6.5.0

packages:
  common: !include common/common.yaml

# external_components:
#   - source:
#       type: git
#       url: https://github.com/MichaKersloot/esphome_custom_components
#     components: [ esp32_camera ]

esp32_camera:
  name: My Camera
  external_clock:
    pin: 0
    frequency: 20MHz
  i2c_pins:
    sda: 26
    scl: 27
  data_pins: [5, 18, 19, 21, 36, 39, 34, 35]
  vsync_pin: 25
  href_pin: 23
  pixel_clock_pin: 22
  # power_down_pin: 32

switch:
  - platform: gpio
    pin: 32
    # restore_mode: ALWAYS_ON
    # id: "cam_power_down"
    name: "${name} Enable CAM"

# esp32_camera_web_server:
#   - port: 8080
#     mode: stream
#   - port: 8081
#     mode: snapshot