substitutions:
  device: tv-light
  name: TV Light
  area: Living Room / Kitchen
  comment: "${area}: TV Rack Light"

esphome:
  name: mcu-${device}
  friendly_name: ${name}
  area: ${area}
  comment: ${comment}

esp8266:
  board: esp8285

packages:
  common: !include common/common_esp8266.yaml

## H801 LED module
# Function 	Pin 	  Channel
# R 	      GPIO15 	PWM1
# G 	      GPIO13 	PWM2
# B 	      GPIO12 	PWM3
# W1 	      GPIO14 	PWM4
# W2 	      GPIO04 	PWM5
# LED D1 R 	GPIO05 	
# LED D2 G 	GPIO01

light:
  - platform: status_led
    id: status_led_id
    pin: 5
  - platform: monochromatic
    name: Strip
    output: pwm_cold_white
    effects:
      - flicker:
          name: Flicker
          alpha: 95%
          intensity: 1.5%
      - strobe:
          name: Slow Strobe
      - strobe:
          name: Fast Strobe
          colors: 
            - state: true
              duration: 100ms
            - state: false
              duration: 100ms

output:
  - platform: esp8266_pwm
    id: pwm_blue
    pin: GPIO12
  - platform: esp8266_pwm
    id: pwm_red
    pin: GPIO15
  - platform: esp8266_pwm
    id: pwm_green
    pin: GPIO13
  - platform: esp8266_pwm
    id: pwm_cold_white
    pin: GPIO14
  - platform: esp8266_pwm
    id: pwm_warm_white
    pin: GPIO04