substitutions:
  device: lightening
  name: Lightening detector
  name_short: Lightening
  area: DEV
  comment: "${area} | Lightening"

esphome:
  name: mcu-${device}
  area: ${area}
  comment: ${comment}
  
esp32:
  board: m5stack-atom
  # board: m5stamp-pico
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0

external_components:
  - source: components

packages:
  common: !include common/common.yaml

i2c:
  # # - id: i2c0
  # sda: 32
  # scl: 33
  # scan: true #false
  # frequency: 100kHz
  # - id: i2c1
  sda: 25
  scl: 22
  scan: true
  # frequency: 100kHz

as3935_i2c:
  irq_pin: 26

binary_sensor:
#   - platform: gpio
#     # name: ${name} Button
#     pin:
#       number: 39
#       inverted: true
  - platform: as3935
    name: Storm Alert

light:
  - platform: esp32_rmt_led_strip
    # name: "${name} LED"
    id: neo
    rgb_order: GRB
    pin: 27
    num_leds: 1
    chipset: ws2812
    restore_mode: ALWAYS_OFF

sensor:
  - platform: as3935
    lightning_energy:
      name: Lightning Energy
    distance:
      name: Storm Distance

