substitutions:
  device: vehicle-honda-pcx125
  name: Vehicle Honda PCX125
  area: Outside
  comment: "${area}, Beacon | Honda PCX125"

esphome:
  name: mcu-${device}
  friendly_name: ${name}
  area: ${area}
  comment: ${comment}

packages:
  base: !include common/vehicle_base.yaml
  logger: !include common/logger.yaml

esp32_ble_beacon:
  type: iBeacon
  uuid: !secret ble_beacon_honda_uuid
  major: !secret ble_beacon_honda_major
  minor: !secret ble_beacon_honda_minor
