substitutions:
  device: cam-1
  name: Cam 1
  area: DEV
  comment: "${area} | Camera"

esphome:
  name: mcu-${device}
  friendly_name: ${name}
  area: ${area}
  comment: ${comment}

esp32:
  # board: esp32cam
  variant: esp32
  framework:
    type: esp-idf

packages:
  common: !include common/common.yaml

i2c:
  id: i2c_bus
  sda: 26
  scl: 27
  scan: true

psram:
  mode: quad
  speed: 40MHz

esp32_camera:
  name: Camera
  external_clock:
    pin: 0
    frequency: 20MHz
  i2c_id: i2c_bus
  data_pins: [5, 18, 19, 21, 36, 39, 34, 35]
  vsync_pin: 25
  href_pin: 23
  pixel_clock_pin: 22
  # power_down_pin: 32

switch:
  - platform: gpio
    pin: 32
    restore_mode: ALWAYS_ON
    # id: "cam_power_down"
    name: Enable

# esp32_camera_web_server:
#   - port: 8080
#     mode: stream
#   - port: 8081
#     mode: snapshot
