---
substitutions:
  device: apollo-dev
  name: Apollo DEV
  area: DEV
  comment: --

esphome:
  name: mcu-${device}
  friendly_name: ${name}
  area: ${area}
  comment: ${comment}
  # on_boot:
  #   - priority: 800
  #     then:
  #       - lambda: |-
  #           id(display_tft).enable();
  #           id(display_tft).transfer_byte(0x11);
  #           id(display_tft).disable();

esp32:
  variant: esp32c6
  flash_size: 8MB
  framework:
    type: esp-idf

packages:
  common: !include common/common.yaml

switch:
  - platform: gpio
    id: accessory_power
    internal: true
    name: Accessory Power
    pin: 4
    restore_mode: ALWAYS_ON
    setup_priority: 2000

web_server:
  version: "3"
