---
substitutions:
  device: apollo-dev
  name: Apollo DEV
  area: DEV
  comment: --

esphome:
  name: mcu-${device}
  friendly_name: ${name}
  area: ${area}
  comment: ${comment}

esp32:
  variant: esp32c6
  flash_size: 8MB
  framework:
    type: esp-idf

packages:
  common: !include common/common.yaml

switch:
  - platform: gpio
    id: accessory_power
    internal: true
    name: Accessory Power
    pin: 4
    restore_mode: ALWAYS_ON
    setup_priority: 2000

web_server:
  version: "3"

light:
  - platform: esp32_rmt_led_strip
    name: RGB LEDs
    pin: 14
    id: rgb_leds
    chipset: WS2812
    num_leds: 10
    rgb_order: GRB
    rmt_symbols: 48
    
  - platform: esp32_rmt_led_strip
    name: Onboard RGB LED
    pin: 5
    id: onboard_rgb_led
    chipset: WS2812
    num_leds: 1
    rgb_order: GRB
    rmt_symbols: 48

output:
  - platform: ledc
    pin: 18
    id: buzzer_output

rtttl:
  - output: buzzer_output
    id: rtttl_player
