substitutions:
  device: vehicle-toyota-auris-ts
  name: Vehicle Toyota Auris TS
  area: Outside
  comment: "${area}, Beacon | Toyota Auris TS"

esphome:
  name: mcu-${device}
  friendly_name: ${name}
  area: ${area}
  comment: ${comment}
  on_boot:
    then:
      - if:
          condition:
            - binary_sensor.is_off: button
          then:
            - wifi.disable:

packages:
  base: !include common/vehicle_base.yaml
  wifi: !include common/wifi.yaml
  logger: !include common/logger.yaml
  ota: !include common/ota.yaml

binary_sensor:
  - platform: gpio
    id: button
    filters:
      - invert:
    pin: 39

esp32_ble_beacon:
  type: iBeacon
  uuid: !secret ble_beacon_toyota_auris_uuid
  major: !secret ble_beacon_toyota_auris_major
  minor: !secret ble_beacon_toyota_auris_minor
