substitutions:
  device: dev-temp
  name: Dev Temp
  comment: "DEV"
  
esphome:
  name: mcu-${device}
  comment: ${comment}

esp32:
  board: esp32doit-devkit-v1
  framework:
  #   type: arduino
    type: esp-idf

external_components:
  - source: components

packages:
  common: !include common/common.yaml

switch:
  - platform: gpio
    pin: GPIO27
    id: sensor_power
    restore_mode: ALWAYS_ON

one_wire:
  - platform: gpio
    pin: GPIO25

sensor:
  - platform: dallas_temp
    name: $name Dallas
    id: temp
    update_interval: 10 s